ARDUINO_DIR = /usr/share/arduino
#
# Board Type
# ----------
# NOTE THAT IF YOU CHANGE BOARD YOU SHOULD DO A MAKE CLEAN!!)
# atmega168    Arduino NG or older w/ ATmega168
# atmega328    Arduino Duemilanove or Nano w/ ATmega328
# atmega8      Arduino NG or older w/ ATmega8
# bt           Arduino BT w/ ATmega168
# bt328        Arduino BT w/ ATmega328
# diecimila    Arduino Diecimila, Duemilanove, or Nano w/ ATmega168
# fio          Arduino Fio
# lilypad      LilyPad Arduino w/ ATmega168
# lilypad328   LilyPad Arduino w/ ATmega328
# mega         Arduino Mega (ATmega1280)
# mega2560     Arduino Mega 2560
# mini         Arduino Mini
# pro          Arduino Pro or Pro Mini (3.3V, 8 MHz) w/ ATmega168
# pro328       Arduino Pro or Pro Mini (3.3V, 8 MHz) w/ ATmega328
# pro5v        Arduino Pro or Pro Mini (5V, 16 MHz) w/ ATmega168
# pro5v328     Arduino Pro or Pro Mini (5V, 16 MHz) w/ ATmega328
# uno          Arduino Uno
#BOARD_TAG    = atmega168
BOARD_TAG    = uno

ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = LiquidCrystal
include /usr/share/arduino/Arduino.mk
